name: find_my_work
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  equatable: ^2.0.0
  freezed_annotation: ^0.14.1
  cloud_firestore: ^1.0.1
  firebase: ^9.0.0
  firebase_core: ^1.0.1
  firebase_database: ^6.1.0
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  flutter_bloc: ^6.1.3
  get_it: ^6.0.0
  injectable: ^1.2.0
  supercharged: ^2.0.0
  flushbar: ^1.10.4
  uuid: ^3.0.1
  auto_route: ^1.0.1
  kt_dart: ^0.9.0
  json_annotation: ^4.0.0
  rxdart: ^0.26.0


dev_dependencies:
  build_runner:
  freezed: ^0.14.1
  lint: ^1.5.3
  injectable_generator: ^1.2.0
  auto_route_generator: ^1.0.1
  json_serializable: ^4.0.2


flutter:
  uses-material-design: true

